CREATE TABLE TRANSFERENCIA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_REMETENTE BIGINT NOT NULL,
    ID_DESTINATARIO BIGINT NOT NULL,
    VALOR DECIMAL(19,2) NOT NULL,
    DATA_TRANSFERENCIA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_TRANSFERENCIA_REMETENTE FOREIGN KEY (ID_REMETENTE) REFERENCES CONTA(ID),
    CONSTRAINT FK_TRANSFERENCIA_DESTINATARIO FOREIGN KEY (ID_DESTINATARIO) REFERENCES CONTA(ID)
);